baseURL = 'https://oboudry.github.io/notes/'
languageCode = 'fr-CH'
title = 'Mes Notes'
theme = "PaperMod"
publishDir = "docs"
[taxonomies]
  tag = "tags"
  category = "categories"
[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "notes"
    name = "Notes"
    url = "/note/"
    weight = 2

  [[menu.main]]
    identifier = "iac"
    name = "Infra as Code"
    url = "/infra-as-code/"
    weight = 3

  [[menu.main]]
    identifier = "sap"
    name = "SAP"
    url = "/sap/"
    weight = 4

  [[menu.main]]
    identifier = "divers"
    name = "Divers"
    url = "/divers/"
    weight = 5

  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 10
[params]
  mainSections = ["infra-as-code", "sap", "divers"]
